# Generated by Django 4.0.6 on 2022-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_products_src_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='src',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
